import {
  Archive,
  Bed,
  BedDouble,
  Bike,
  ChevronDown,
  Flame,
  Heart,
  Key,
  LayoutGrid,
  type LucideIcon,
  MapPin,
  PawPrint,
  Share,
  ShowerHead,
  Sofa,
  Trees,
  UtensilsCrossed,
  WashingMachine,
  Wifi,
} from 'lucide-react';

export {
  Archive as StorageIcon,
  Bed as BedSingleIcon,
  BedDouble as BedDoubleIcon,
  Bike as BikeIcon,
  ChevronDown as ChevronDownIcon,
  Flame as HeatingIcon,
  Heart as HeartIcon,
  Key as KeyIcon,
  LayoutGrid as GridIcon,
  MapPin as MapPinIcon,
  PawPrint as PawIcon,
  Share as ShareIcon,
  ShowerHead as ShowerIcon,
  Sofa as SofaIcon,
  Trees as GardenIcon,
  UtensilsCrossed as KitchenIcon,
  WashingMachine as WasherIcon,
  Wifi as WifiIcon,
};

export const AMENITY_ICONS: Record<string, LucideIcon> = {
  wifi: Wifi,
  kitchen: UtensilsCrossed,
  washer: WashingMachine,
  heating: Flame,
  storage: Archive,
  bike: Bike,
  garden: Trees,
  shower: ShowerHead,
};
